name: Run main.py

on:
  schedule:
    - cron: '30 19 * * *' # runs every 2 hours

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute py script # run main.py
        run: |
          echo "Checking environment variables..."
          if [ -z "$SOME_SECRET" ]; then echo "SOME_SECRET is not set"; else echo "SOME_SECRET is set"; fi
          if [ -z "$EMAIL_FROM" ]; then echo "EMAIL_FROM is not set"; else echo "EMAIL_FROM is set"; fi
          if [ -z "$EMAIL_TO" ]; then echo "EMAIL_TO is not set"; else echo "EMAIL_TO is set"; fi
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 